### ISSUE TITLE
Request for Source Code of app.js and vendor.js for Customization

### ISSUE THREAD

**Issue by KojiAndoJC** [sfu-db/dbt-lineagex#2]
I am looking to personally customize the data lineage view in the dbt-lineagex project to add descriptions to the data models for my own use. Currently, only the compiled versions of `app.js` and `vendor.js` are available. Could the original source files be shared to facilitate this customization?

Thank you.

**Comment by zshandy** [comment]
Hi,

Thank you very much for taking interest in LineageX!

Here is the source code for the frontend(https://github.com/zshandy/lineage-dag), and I am always taking suggestions for updating the frontend too(not much of a frontend developer)! Please note that contributing and referencing columns are not exactly distinguished by dbt-lineagex and lineagex with a database conn(will be updated soon to match the no conn version).

Cheers,

**Comment by KojiAndoJC** [comment]
Thank you for your reply, and I apologize for my late response. I will create a separate issue in the dbt-lineagex project to request a new feature, as it affects dbt-lineagex, lineagex, and lineage-dag.
